// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-playground/validator"
	"github.com/google/wire"
	"hot_news_2/app"
	"hot_news_2/controller"
	"hot_news_2/repository"
	"hot_news_2/service"
	"net/http"
)

// Injectors from injector.go:

func InitializedServer() *http.Server {
	userRepository := repository.NewUserRepository()
	db := app.NewDB()
	validate := validator.New()
	userService := service.NewUserService(userRepository, db, validate)
	userController := controller.NewUserController(userService)
	categoryRepository := repository.NewCategoryRepository()
	categoryService := service.NewCategoryService(categoryRepository, db, validate)
	categoryController := controller.NewCategoryController(categoryService)
	articleRepository := repository.NewArticleRepository()
	articleService := service.NewArticleService(articleRepository, db, validate)
	articleController := controller.NewArticleController(articleService)
	commentRepository := repository.NewCommentRepository()
	commentService := service.NewCommentService(commentRepository, db, validate)
	commentController := controller.NewCommentController(commentService)
	likeRepository := repository.NewLikeRepository()
	likeService := service.NewLikeService(likeRepository, db, validate)
	likeController := controller.NewLikeController(likeService)
	router := app.NewRouter(userController, categoryController, articleController, commentController, likeController)
	server := NewServer(router)
	return server
}

// injector.go:

var userSet = wire.NewSet(repository.NewUserRepository, service.NewUserService, controller.NewUserController)

var categorySet = wire.NewSet(repository.NewCategoryRepository, service.NewCategoryService, controller.NewCategoryController)

var articleSet = wire.NewSet(repository.NewArticleRepository, service.NewArticleService, controller.NewArticleController)

var commentSet = wire.NewSet(repository.NewCommentRepository, service.NewCommentService, controller.NewCommentController)

var likeSet = wire.NewSet(repository.NewLikeRepository, service.NewLikeService, controller.NewLikeController)
